import React from 'react';
// import PropTypes from 'prop-types';
import { Container, Row, Col } from 'react-bootstrap';
import Layout from 'shared/Layout';
import { OuterBody } from 'sharedStyle';

const WhitePaper = () => {
  return (
    <Layout>
      <OuterBody>
        <Container className="page-content">
            <Row className="text-center">
              <Col>
                <h1>Rocket Doctor - The future of Telemedicine</h1>
              </Col>
            </Row>
            <Row>
              <Col>
                <div className="rich-text-block-4 w-richtext">
                  <h3>&nbsp;1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Introduction</h3>
                  <p>Telemedicine is the practice of embracing technology with the medical profession, this basically refers to the integration of medical services with computers, laptops and smart devices such as phones and tablets, providing access to medical professionals through these devices.</p>
                  <p>There are 4 key elements that any Telemedicine application must address and consider.</p>
                  <p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It must provide clinical support.</p>
                  <p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It must overcome geographical barriers, therefore connecting patient and medical professional who are not in the same physical location.</p>
                  <p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It must use of various types of ICT.</p>
                  <p>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It must improve health outcomes.</p>
                  <p>While these four statements are true and generally cover the aims and goals of a competent system, it must be understood that they only really touch the tip of the issues, many other factors are key, one underlying principle that must always be considered is confidentially, your medical data is key personal information and information that must be protected at all costs. &nbsp;</p>
                  <p>Traditionallythere have been several barriers to the concept and uptake of telemedicine,these barriers are now being slowly eroded and the opportunity to develop andtake advantage of this multibillion-dollar market has never been more open tothe correct organizations, we are that organization.</p>
                  <h4>1.1&nbsp;&nbsp;&nbsp;The World Health Organization</h4>
                  <p>The World Health Organization (WHO) has defined Telemedicine as</p>
                  <blockquote><em>“The delivery of health care services,where distance is a critical factor, by all health care professionals using information and communication technologies for the exchange of valid information for diagnosis, treatment and prevention of disease and injuries,research and evaluation, and for the continuing education of health care providers, all in the interests of advancing the health of individuals and their communities”</em>
                  </blockquote>
                  <p>The WHO considered that Telemedicine is a vital tool which needs to be embraced and developed to help get medical assistance to all that need it, it is a means to overcome physical boundaries, financial boundaries and prove top quality access to health care professionals for all.</p>
                  <p>The WHO suggests that the biggest benefit of this technology would in fact be in developing countries where they have limited resources and limited infrastructure. By adapting the telemedicine technology, they would be able to provide greater access to specialists.</p>
                  <h4>&nbsp;1.2&nbsp;&nbsp;&nbsp;Telemedicine Barriers</h4>
                  <p>While the drive has been there, there has previously been some key barriers to the uptake of telemedicine applications, this has included but not limited to,cultural issues, lack of consistency, inability to use complex interfaces. A number of these issues have been addressed and are no longer seen as barriers.The commercial world is becoming more and more focused on remote working and supporting this many smart devices have improved their reliability and human interface mechanism. One major issue that remains is legal concerns over data privacy and how this data is used.</p>
                  <h4>1.3&nbsp;&nbsp;&nbsp;Global Workforce</h4>
                  <p>More and more organization are looking to have a global workforce, one which has &nbsp;no geographical boundaries and one in which all employees, no matter where they call home, are treated in the same manner,this in its self opens up a whole new market place for Telemedicine, a company will still want to ensure that their employees get the best possible medical advice and that they are able to control and off such services to their global workforce, this is only possible by adopting and using the principles of Telemedicine.</p>
                  <h4>1.4&nbsp;&nbsp;&nbsp;Rocket Doctor</h4>
                  <p>The Management team at RocketDoctor have been closely monitoring and studying the way in which telemedicinehas been addressed by several applications and believe that there is a major area for improvement, and it is these areas that shall make RocketDoctor standout and shine.</p>
                  <p>This is a new market with billions of dollars being invested from both private companies and government agencies alike. The correct adaptation will save a healthservice provider millions of dollars, this would be made up from travel time,time to see patients and unnecessary clinic hours which can easily be substituted for actual communication with patients.</p>
                  <p>Within the private sector the opportunity to use and exploit this technology is limitless, major industries, such as oil and gas, while working in remote locations would be able to adopt this technology to get their staff assessed by medical professional without the added risk and cost of possibly unnecessary medical evacuations just to find out a simple assessment was required.</p>
                  <p>RocketDoctor is an organization that is led and driven by an emergency room physician who has vast experience of international work, having worked in a number of different countries, ranging from South Africa, UK and Asian countries. With the improve technology and reliability of service and accessibility via the ever-growing smart phone market users are looking to do more and achieve more with their smart phones.</p>
                  <p>Added to this is the increased use of remote workers who are demanding better access to medical professionals, this can only be achieved by the adoption and growth of the Telemedicine application. Rocket Doctor will embrace the latest technology for block chain management of records, while providing the key interaction required to enable a medical professional to provide accurate assessments, the focus will be both the public sectors, health service providers and major corporation that work in or have workers in remote locations. RocketDoctor is in a unique position to be able to assess the competition and see the areas they have struggled with outdated technology, apply more bleeding edge technology and drive the way forward to open up the access to the marketplace.</p>
                  <h3>2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;How can telemedicine Help you?</h3>
                  <p>The major questions and objective of any good telemedicine application is how to share accurate medical data with medical professionals in such a manner that it adds value and enable the medical professional to provide an accurate assessment of the individuals condition, furthermore this information must be kept in a secure manner, after all this is private and sensitive data, it is data that must be accessible and reliably accessed.</p>
                  <h4>2.1&nbsp;&nbsp;&nbsp;Medical Records</h4>
                  <p>No medical assessment can be complete without the basic medical records, no matter if this is basic history or images from previous injures, test results, for people with complex medical history this information could be vital to ensuring an accurate diagnoses and saving them a lot of time, money and possibly pain. RocketDoctor has considered this to be one of the key elements and will beemploying the latest block chain technology to ensure not only are the records accessible and up to date but are held in a secure manner thus ensuring the patients confidential information remains confidential at all times.</p>
                  <h4>2.2&nbsp;&nbsp;&nbsp;Global Workforce</h4>
                  <p>As corporations embrace new technology the potential for a remote workforce become sever more the reality, more companies are not just relocating parts of their business but are making whole departments remote worker based, with this embracing of new technology comes new issues, how can you ensure your workforce's well, if you traditional have a clinic in your office, which most major corporations do, how can you ensure your staff have access to professional medical assessments and advice. This is achievable by the adoption of and supporting the principles of Telemedicine, not only can you ensure your staff get the same professional level but you can reduce costs, there are no travel costs, no expensive double dip on procedures, all this is saving time, effort and costs for the company and the individual.</p>
                  <h3>3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rocket Doctor</h3>
                  <p>What is required is a stable and reliable platform, one that will help a user control and manage their medical records, one that will enable a user to get access to medical professionals in a manner that is both cost effective, timely and promotes well being.</p>
                  <h4>3.1&nbsp;&nbsp;&nbsp;Medical Records</h4>
                  <p>The accurate use of medical records and medical history for a patients cannot be under estimated, delays can cost lives, RocketDoctor fully understands and is driven to ensure not only that your personal information is kept secure and safe but is also accessible when required and that the patients has the ability to share the most accurate information with the medical professional, this will be achieved &nbsp;by adopting the latest technology and standards for blockchain management of data, any data entering locally on a device will automatically become available to all authorized view of the patients data, thus ensuring the latest information is always being accessed by the patients authorized medical professionals. This method not only will permit the patients data to be accessed by all medical professionals, but when specialist input is required the local medical professional and the specialist can be viewing the most accurate data with the patient directly, this would be a logistical nightmare without the use of RocketDoctor will enable this in a more cost effective and productive manner.</p>
                  <h4>3.2&nbsp;&nbsp;&nbsp;Medical assessments</h4>
                  <p>As the world becomes a smaller place and we all travel more, and travel further away from home it is key that we still have access to our medical records and our own medical professionals, individuals with complex medical history have normally had to ensure that they take the relevant information with them and this can be bulky and easily lost, with RocketDoctor the patient will always have access to the medical record and a medical assessment, they will be able to talk directly with either their own doctors and other medical professionals or will be able to authorize that a local medical professional can consult with their own medical professional back home. This will save the patient, time,money and possibly much more.</p>
                  <p>RocketDoctor will give patients the ability to talk directly with medical professional via its own video conferencing facility, which shall be end to end encryption to ensure the conversation remains private and confidential.</p>
                  <h4>3.3&nbsp;&nbsp;&nbsp;Medical devices</h4>
                  <p>RocketDoctor will support the use of commonly used devices and is in the process of developing interfaces with other medical devices that are currently being used.This will ensure that follow up conversations and appointments, made using RocketDoctor interface, have all the most accurate information available and ensure that the medical professionals have the data at their fingertips, quite literally.</p>
                  <h4>3.4&nbsp;&nbsp;&nbsp;Appointments</h4>
                  <p>No telemedical system would be of value if you could not schedule and be reminded of appointments, while all consultations could be carried out via the application we do appreciate that there will be times, for test and other procedures, where the patient will be required to travel, RocketDoctor will keep a record of all your appointments, not just virtual but actual appointments and will enable a report to be entered and recorded. For a test imaging results may be required and RocketDoctor supports a varied number of formats to ensure that the data is always at hand.</p>
                  <h3>4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ICO v STO</h3>
                  <p>Right now, RocketDoctor is in its infancy,we are prototyping a number of key elements and looking at ways to establish funding for the full system.</p>
                  <p>At present the two major methods for funding development such as this are ICO (Initial Coin Offering) and STO(Security Token Offering). Both are cryptocurrency. The investor is purchasing coins, sharesin the company which upon successful completion and launch would then return their investment by the uptake of the users.</p>
                  <p>The question is which one should be used?</p>
                  <h4>4.1&nbsp;&nbsp;&nbsp;ICO</h4>
                  <p>ICO really took off in 2017 and has been reaching some amazing numbers, in the first half of 2019 $13.7 billion has been raised by ICOs, figures supplied from PwC, while it still remains true that venture capitals deals still dwarf these numbers for developments such as RocketDoctor cryptocurrency is seen as the more suitable method.</p>
                  <p>It would be a fair assumption that given the success and large investments that ICOs would continue on their predicted growth trajectory, while an investor may not fully understand the technology,they do understand trends, and with more and more investors the trend is clear.However the SEC have an issue with ICO, ICOs where, are, a tactic for companies to get their protocol tokens into the hands of users, which is a good plan,users are effectively pre buying time with the App before it has been developed, thus helping the company fund the development of the application. The investors are investing in the end worth of the coins, for example they purchase a coin now for $1 this money is given to company developing the application and then once the application is released that coin’s value, which would be used to purchase services and screen time with RocketDoctor would then have a different value, possible $1.3, the investor will have made 30% profit.The SEC views these as sales of Securities and not utilities, which means they have no security, this is of concern to the SEC. &nbsp;</p>
                  <h4>4.2&nbsp;&nbsp;&nbsp;STO</h4>
                  <p>The concept of Security Token Offering,STO, has been around as long as ICO, the term was really first used in 2017, an STO is similar to an ICO in that you are offering crypto tokens built on a blockchain, however STOs are not considered to be the sale of coins but the sale of securities. Another key difference is that STO participants are investors, not users, who pay and receive security, which is represented by a token, to enable this a company must be registered with the SEC or use an exemption. As this is more focused around a security element and investors, not the public, it is not the best option for many, day trading is not permitted and there are some strict limits.</p>
                  <h3>5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;RocketDoctor’s Technology</h3>
                  <p>RocketDoctor will be employing the latest technology to ensure that patient data remains secure and all communication is conducted in a safe and reliable manner. RocketDoctor will be embracing Augmented Reality, Artificial Intelligence and block-chain.</p>
                  <h4>5.1&nbsp;&nbsp;&nbsp;Augmented Reality (AR)</h4>
                  <p>Augmented Reality (AR) has been a major breakthrough in being able to have real world view of objects displayed in such a manner that you can truly understand their dynamics; AR is the integration of digital information from the environment in real time. AR differs from virtual reality, which is an artificial environment, AR uses the environment and overlays information on top it. Another major difference is that AR does not require any specific hardware and most modern devices are able to display images using AR technology.</p>
                  <p>This improved technology is a major breakthrough in the telemedicine industry, AR will enable users of RocketDoctor to be examined by a doctor as if they were in the same room, injures will be visible in a manner which has never before been possible and RocketDoctor is the only telemedicine application that will be employing AR within its standard technology platform.</p>
                  <p>The Red Cross in American have employed this technology at a minor level, at the moment it is only being used to help with blood donations, RocketDoctor intends to employ this technology to helping doctors with the consultations and examinations, remotely, of their patients,when used in an emergency situations and remote locations this will be a lifesaving element that only exists within RocketDoctor.</p>
                  <h4>5.2&nbsp;&nbsp;&nbsp;Blockchain</h4>
                  <p>As the name would indicate this is a method of storing chunks of data together in a chain. Blockchain has become very popular in the field of cryptocurrencies, this is due to high level of security. When a block is created it has 3 basic elements; its hash, the data and the previous blocks hash.</p>
                  <p>1)&nbsp;&nbsp;The hash is considered the blocks fingerprint, it is a unique alphanumeric code, usually 64 characters long, when a block is created so is its hash, and every time the data is changed the hash is modified as well.</p>
                  <p>2)&nbsp;&nbsp;Data, depending on the use this could be information about a transaction, or a small part of a data chain used to create a complete set of medical records.</p>
                  <p>3)&nbsp;&nbsp;Previous Blocks hash, this is how the chain is created, it stores the previous blocks hash.</p>
                  <p>What makes this so secure is that if an individual hacks into a chunk of data, the hash code is changed, when the next block is accessed it will check the hash code, if this is different to the stored hash code access will be denied. A further level of security that is employed withblockchain is that unlike traditional data storage, such as servers and database, blockchain employs peer-to-peer, this means that anybody can join and all those authorized will have the same data, now when somebody wish to hack they have to hack all the locations where the data is stored, since every block has a unique hash and this is used to ensure the integrity of the chain. This makes blockchain data some of, if not the most secure method of storing secure information.</p>
                  <p>RocketDoctor shall be employing blockchain techniques to all of its records, not just purchased time but all medical records thus ensuring the patients records remain locally accessible but are secure, if a medical center has been hacked your records will remain secure on your devices,and the hacker will not able to access it, this data will then be restore and nothing will have been lost, other than at most a single block of information.</p>
                  <h4>5.3&nbsp;&nbsp;&nbsp;Artificial Intelligence (AI)</h4>
                  <p>Artificial Intelligence is the process in which a computer is able to interact with a human, within the telemedicine industry a chat bots are common, they will carry out initial assessments and ensure that the patient is seen by the required specialist. AI will be able to carry out basic assessment, and when employed in emergency situations will be able to carry out simple triage, thus ensure priority is given to the relevant patients. “ChatBots”, AI interaction, is very common these days and many of us are used to interacting with them, banks, online shopping, taxi companies,travel companies etc. all make use of these, in a very basic form, to help manage and control interaction with their customers, RocketDoctor will take this concept beyond basic interaction and will look to employ a level of sophistication that will ensure the interaction is accurate and will be able to look at first level assessments, for new patients this may included collectingmedical history.</p>
                  <h4>5.4&nbsp;&nbsp;&nbsp;Voice Interaction</h4>
                  <p>No modern application would be classifieds leading the way if it did not incorporate voice recognition, with the telemedicine industry RocketDoctor will be leading the way with this, not only with our &nbsp;Chatbots be able to interact and carry out basic triage assessments and ensure the correct medical professional is contacted but RocketDoctor will also be fully voice activated if you should so desire,and in times this could be a lifesaving faculty, voice controlled chatbots can help ensure the patient can talk with and ensure that the instructs given are being followed, if we look at the situation of patient having a medical emergency, RocktDoctor’s Chatbot will be able to response to the patient, guided them, while in the background the technology is contacting the relevant medical professional, giving them updates and handing over in a more effective manner.</p>
                  <p>The key factor here will be that RocketDoctor’s chatbot will work with standard conversation and not simple commands, it would need to work more like Alexa then just having a list of simple commands the user can interact, using regular speech. &nbsp;</p>
                  <h3>6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Virtual Hospitals</h3>
                  <p>What is a Virtual Hospital, are we really just talking about telemedicine, mostly,but a true virtual hospital goes beyond just telemedicine. Joseph Kvedar MD, vicepresident of connected health at Partners Health Care in Massachusetts, He’s been involved with connected health technologies for nearly 25 years, has given the following example of his interpretation of what a virtual hospital is, he has used the e-ICU as an example:</p>
                  <blockquote><em>“You have a group of intensive care physicians in a call center environment—instrumented with lots and lots of screens and technology—and they’re guiding other providers,usually ICU nurses, in an ICU that’s remote from them.”</em>
                  </blockquote>
                  <p>Mercy Victual Care Center has taken a different approach, it is a freestanding facility staffed with healthcare professionals, this facility is over 125,000 square foot, St Lukes has open a telehealth service, located in Idaho, this provides ambulatory, acute and post acute services. Inter mountains Connect Care Pro will open a 20,000 square foot facility that will house 150 clinicians.</p>
                  <p>The term virtual can be misleading, the hospitals are real, the patients can physically go and have tests carried out, some have beds such as you would expect in a traditional hospital, the main difference is that medical professional don’thave to be there to give you the service, they can be connected from any wherein the world. With the USA 65% of hospitals connect patients and consulting practitioners remotely, using video conferencing technology, and with the new advances in AR this has become more effective and efficient for both thepatients and the medical professionals.</p>
                  <h4>6.1&nbsp;&nbsp;&nbsp;RocketDoctor and VirtualHospital</h4>
                  <p>The long-term goal of any true telemedicine or telehealth giver has to be global connection between patient and a doctor, we see that a virtual hospital can address the main shortfalls of a traditional hospital environment.</p>
                  <h4>6.1.1 Open 24 Hours a day</h4>
                  <p>At present most hospitals operate their specialist consulting hours during normal business hours, which can be inconvenient for some and can just mean less time seeing patients, a virtual hospital would be open 24hrs day, with access to medical professional through video chat using a smartphone or similar devices, such as a tablet or even a home PC.</p>
                  <h4>6.1.2 Specialist Service More Accessible</h4>
                  <p>No longer would it be the case of the relevant specialist has gone home and the need to call him out and get a return trip to the hospital, by employing telemedicine technology, specifically AR reality within RocketDoctor these specialist will be able to give life save information, get a really understanding of the medical situation and inevitable saving lives.</p>
                  <h4>6.1.3 Costly Transfers</h4>
                  <p>Transferring of a patient from one hospital to another, by helicopter or by ambulance, is normally to enable a specialist to be able to make an assessment and start the right course of action, by employing the telemedicine technology held with RocketDoctor this would no longer be necessary, a doctor in a neighboring state or even in a different country would be able to assess the patient using the AR technology and ensure that the correct course of action is being employed. Thisin its self could save a patient many thousands, within the USA the averagecost of transfer a critical patient is $18,000 and this does not included thecosts involved for the family members that will want to be by the patientsside.</p>
                  <h4>6.1.4 Connected</h4>
                  <p>The fact thattechnology and internet access is becoming global is a major factor in theuptake and development of the telemedicine industry, the aim is the bringmedical expertise’s to the patient where and whenever need, no longer will itnow be necessary to fly and or travel for hours just to see a doctor or othermedical health professional RocketDoctor will place this ability within yourhand, by employing the latest technology you will have access to the medicalprofessional you need, no matter where they are in the world and no matterwhere you are in the world. This is key for many, expat, major corporations,the avid traveler and Mr. and Mrs. Smith just going on holiday, now withRocketDoctor you have 24hr 7 days a week 52 week a year access to the bestmedical professionals in the world and with the deployment and creation ofvirtual hospitals this works the other way around, for a medical professional,you always have access to your patient to ensure they are getting the care youwould expected them to receive.</p>
                  <h3>7. Competitors</h3>
                  <p>The concept of Telemedicine has been around for a number of years, there are a number of applications, the following is a breakdown of the main ones.None of which are in fact direct competitors for the concept of RocketDoctor.</p>
                  <p><strong>MedicalChain</strong>
                  </p>
                  <p>Started in 2016, to date does not have an app which can be downloaded. Has been funded by cryptocurrency, current investment level is not known.</p>
                  <p><strong>Amwell: Doctor Visits 24/7</strong>
                  </p>
                  <p>Amwell offers quality medical care on demand. You can schedule appointments, often with next-day availability. Before insurance, Amwell services vary between $69 or less for urgent care — up to $200 for an online psychiatric visit.</p>
                  <p><strong>Maple – 24/7 Online Doctors</strong>
                  </p>
                  <p>This is a Canadian based application the focus of which is just to get a consultation with a doctor.</p>
                  <blockquote><em>“Maple is a healthcare app for fast,convenient, around-the-clock access to licensed doctors in Canada. Just request a consultation with a physician, and you’ll immediately be connected to a doctor through live chat or video on the app’s secure platform. Get a diagnosis, prescription, sick note, or medical advice in minutes.</em> “</blockquote>
                  <p><strong>Babylon Health</strong>
                  </p>
                  <p>Is really focused around the NHS within the UK, they have started to look outside but at present they are purely UK focused.Funded by ICO, level of funding not known. Last release stated that the company was valued at $2bn.</p>
                  <blockquote><em>“For those in the U.K., the Babylon app gives you access to NHS healthcare and appointments with qualified general practitioners. Speak to a GP around the clock and on weekends when you need advice or to get a diagnosis via video or phone appointments. Prescriptions can also be sent directly to your local pharmacy for collection within an hour.Babylon also has a symptom checker that analyzes millions of symptoms in seconds.”</em>
                  </blockquote>
                  <p><strong>Doctors On Demand</strong>
                  </p>
                  <p>This is a USA based, focus is around connecting with a doctor, it does not look to store and give you the full service, it does have supporting apps.</p>
                  <blockquote><em>“Get face to face with a doctor,psychiatrist, or psychologist whether you have insurance or not. The app’s providers are licensed physicians, psychiatrists, and psychologists, and they can treat hundreds of issues online through video. Your doctor will take your history and symptoms, perform an exam, and recommend treatment”</em>
                  </blockquote>
                  <p><strong>Practo</strong>
                  </p>
                  <p>Practo is focused on providing a list of medical practitioners in your given area.</p>
                  <p>RocketDoctor believes that none of the competitors offer the full package, the ability to maintain and control your medical records, the ability to interact directly with medical professionals irrespective of geographical boundaries, this is a market which has yet to be touched, one that is open to both health service providers and major corporations, one that has a potential to be worth millions of dollars in user time and services. &nbsp;</p>
                  <h3>8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Conclusion</h3>
                  <p>From here the company will look to develop a prototype and will then use that to secure funding to take the application to the marketplace. Both a smart phone,supporting both Android and iPhone applications will be developed along with Windows and MAC based applications.</p>
                  <p>RocketDoctor will deliver an application that fills the gap left by the others, it shall &nbsp;give you the ability to have secure access to your medical records, share thisinformation with medical professional you authorize. RocketDoctor shall also provide both the patient and medical professionals the ability to discuss online, via secure end to end encryption, the case before them, be this in a doctor patient meeting or a meeting between two doctors.</p>
                  <p>RocketDoctor will embrace bleeding edge technology to ensure that its customers have the best possible experience and that the services are reliable and steady.</p>
                  <p>The market for RocketDoctor will be both private and public sector, major private corporations that deploy staff to remote locations, such as Oil and Gas, Mining, MerchantNavy, public sector shall include hospitals and other medical providers.</p>
                </div>
              </Col>
            </Row>
        </Container>
      </OuterBody>      
    </Layout>
  )
}

WhitePaper.propTypes = {
}

export default WhitePaper
